apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "anaf-app.fullname" . }}-config
  labels:
    {{- include "anaf-app.labels" . | nindent 4 }}
data:
  DB_HOST: {{ .Values.backend.env.DB_HOST | default (include "anaf-app.mysql.serviceName" .) | quote }}
  DB_PORT: {{ .Values.backend.env.DB_PORT | quote }}
  DB_NAME: {{ .Values.mysql.auth.database | quote }}
  DB_USER: {{ .Values.mysql.auth.username | quote }}
  REACT_APP_API_URL: {{ .Values.frontend.env.REACT_APP_API_URL | quote }}
