{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "anaf-app.mysql.serviceName" . }}
  labels:
    {{- include "anaf-app.labels" . | nindent 4 }}
    {{- include "anaf-app.mysql.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.mysql.service.type }}
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    {{- include "anaf-app.mysql.selectorLabels" . | nindent 4 }}
{{- end }}
