apiVersion: v1
kind: Secret
metadata:
  name: {{ include "anaf-app.fullname" . }}-secret
  labels:
    {{- include "anaf-app.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-root-password: {{ .Values.mysql.auth.rootPassword | b64enc | quote }}
  mysql-password: {{ .Values.mysql.auth.password | b64enc | quote }}
  jwt-secret: {{ .Values.backend.env.JWT_SECRET | b64enc | quote }}
